### ISSUE TITLE
Add comparison feature

### ISSUE THREAD

**Issue by chesterhow** [chesterhow/overwatch-telegram-bot#11]
Create new command `/compare` for users to compare stats between 2 players

**Comment by Lord-Protector** [comment]
I think I will realize it.

**Comment by chesterhow** [comment]
I haven't found a nice way to display 2 players stats side by side in telegram yet. Since there are only a limited number of characters each line and there aren't many formatting options either. What do you think?

**Comment by Lord-Protector** [comment]
@chesterhow I think about dynamic image generation to realize that. Seems like nice idea, but I don't work with canvases yet :)
