### ISSUE TITLE
Add overview command with image generation via canvas

### ISSUE THREAD

**Issue by L11R** [chesterhow/overwatch-telegram-bot#17]
I think It's will be very useful in groups to get overview information about some player in just one command. Maybe I will realize it in some future.

**Comment by chesterhow** [comment]
Woah image generation! Sounds really cool. But no hurry don't worry about it :)

**Comment by Lord-Protector** [comment]
![2016-12-09_15-25-08](https://cloud.githubusercontent.com/assets/5345489/21049073/b8fe27ca-be23-11e6-9233-f53683d89495.gif)
Some progress.

**Comment by chesterhow** [comment]
Wow looking good! What's this canvas thing you're using?

**Comment by Lord-Protector** [comment]
Just `node-canvas`.

**Comment by Lord-Protector** [comment]
![image](https://cloud.githubusercontent.com/assets/5345489/21075739/7484a4c2-bf2a-11e6-98dd-a0ffe031f8b3.png)

**Comment by Lord-Protector** [comment]
I think it's nearly release candidat :D
![2016-12-11_18-55-41](https://cloud.githubusercontent.com/assets/5345489/21081260/a9348760-bfd3-11e6-8b5a-a6c710f32b4d.gif)

**Comment by Lord-Protector** [comment]
![photo_2016-12-11_22-37-40](https://cloud.githubusercontent.com/assets/5345489/21082727/7da34770-bff2-11e6-91e4-e3671d81328e.jpg)
Beta 3.

**Comment by chesterhow** [comment]
wow you're really fast! 👍🏼

**Comment by Lord-Protector** [comment]
I think I will need some you help in "refactoring". I am not js-programmer, so write code like I know. Maybe violate some rules or somethink like that. Now I fix some minor bugs, then I think will do pull request.

**Comment by chesterhow** [comment]
Sure I can help you with that. But I'm a little busy these few weeks, exams and stuff, so I may not be able to work on the bot as quick.
